### ISSUE TITLE
the question about loss

### ISSUE THREAD

**Issue by quickjkee** [mingyuanzhou/SiD-LSG#1]
Hello! Thanks for your interesting work!

I have a question regarding the final distillation loss. The loss you mentioned is the following combination: $\mathcal{L}^{(2)} - \alpha\mathcal{L}^{(1)}$ mostly using $\alpha=1$. However, in this case, the main loss is reduced: $\mathcal{L}^{(2)} - \mathcal{L}^{(1)} = \cancel{\mathcal{L}{(\theta)}} +  ... -  \cancel{\mathcal{L}{(\theta)}} - ...$ according to eq. (15) and (20).

Why do we still get meaningful gradients in this case? Thank you!

**Comment by mingyuanzhou** [comment]
Hi, thanks for your question! While $L(\theta)$ cancels out, there are remaining terms involving $G_{\theta}$, $\phi$, $\psi$, and $\psi^{\*}(\theta)$. The exact theoretical reason for this empirical effectiveness is currently unknown, but we suspect it reintroduces $\psi^{\*}(\theta)$ into the loss function. Consequently, this takes into the consideration of the gradient of $\psi^{\*}(\theta)$ with respect to $\theta$, which, to the best of our knowledge, has not been achievable with any previously proposed loss functions.
