### ISSUE TITLE
Aesthetic6+ missing from huggingface

### ISSUE THREAD

**Issue by Schwartz-Zha** [mingyuanzhou/SiD-LSG#2]
Aesthetic6+, Aesthetic6.25+, Aesthetic6.5+ all seem to be missing from Huggingface, could the authors provide another approach to access them to run this code?

**Comment by mingyuanzhou** [comment]
Data available here:
https://huggingface.co/datasets/dclure/laion-aesthetics-12m-umap 


Script to extract txt files from it:

from datasets import load_dataset
import os

dataset_dir = 'aesthetics'

ds = load_dataset("parquet", data_dir=dataset_dir, split='train')
six_two_five_plus = []
six_five_plus = []
six_plus = []
total = len(ds)
print(f'total {total} records need to be scanned')
percent = int(total / 100)
i = 0
for entry in ds:
  six_plus.append(entry['TEXT'])
  if entry['AESTHETIC_SCORE'] >= 6.25:
    six_two_five_plus.append(entry['TEXT'])
  if entry['AESTHETIC_SCORE'] >= 6.5:
    six_five_plus.append(entry['TEXT'])
  i += 1
  if i % percent == 0:
    print(f'scanned {i / percent}% data')
print(f'got {len(six_plus)} 6.0+, {len(six_two_five_plus)} 6.25+ and {len(six_five_plus)} 6.5+')

percent = int(len(six_plus) / 100)
i = 0
with open(os.path.join(dataset_dir, 'aesthetics_6_plus.txt'), 'wt') as f:
  for row in six_plus:
    i += 1
    f.write(row + '\n')
    if i % percent == 0:
      print(f'generated {i / percent}% 6.0+ data to text file')
  print(f'Generated {len(six_plus)} prompts for 6.0+ score')

percent = int(len(six_two_five_plus) / 100)
i = 0
with open(os.path.join(dataset_dir, 'aesthetics_625_plus.txt'), 'wt') as f:
  for row in six_two_five_plus:
    i += 1
    f.write(row + '\n')
    if i % percent == 0:
      print(f'generated {i / percent}% 6.25+ data to text file')
  print(f'Generated {len(six_two_five_plus)} prompts for 6.25+ score')


percent = int(len(six_five_plus) / 100)
i = 0
with open(os.path.join(dataset_dir, 'aesthetics_65_plus.txt'), 'wt') as f:
  for row in six_five_plus:
    i += 1
    f.write(row + '\n')
    if i % percent == 0:
      print(f'generated {i / percent}% 6.5+ data to text file')
  print(f'Generated {len(six_five_plus)} prompts for 6.5+ score')

**Comment by luolundashu** [comment]
why not use 'ds = load_dataset("dclure/laion-aesthetics-12m-umap"),which is the official script.
