### ISSUE TITLE
pre-computed feature stat for fid eval

### ISSUE THREAD

**Issue by yuanzhi-zhu** [mingyuanzhou/SiD-LSG#4]
Thanks for your great work.

https://github.com/mingyuanzhou/SiD-LSG/blob/main/metrics/sid_fid_and_clip.py#L40
here the `mu_real, sigma_real` will be calculated each time when evaluating, we can do this once and for the MS-COCO-256 dataset.

In this case, it would be great if you can share the stat numpy files, so people can train and evaluate SiD model with prompts only without any image data.

**Comment by yuanzhi-zhu** [comment]
https://github.com/boomb0om/text2image-benchmark/blob/main/T2IBenchmark/datasets/coco2014/__init__.py#L14
can be found here!

**Comment by mingyuanzhou** [comment]
Thanks, Yuanzhi! Indeed some of the evaluations can be optimized to avoid redundant computation. I will keep these in mind in future update of the code
